### ISSUE TITLE
Phase 1bis: Remember to check Singularity MPI/interconnect libraries configuration

### ISSUE THREAD

**Issue by marcodelapierre** [PawseySC/pawsey-spack-config#122]
@dipietrantonio @pelahi @ddeeptimahanti 
please check that the host MPI/interconnect library paths in the Lua modulefiles are updated following OS/Cray updates:  https://github.com/PawseySC/pawsey-spack-config/blob/main/setonix/templates/modules/modulefile.lua#L99-L100

These are required in order for containers to achieve MPI bare-metal performance.

**Comment by dipietrantonio** [comment]
Hi Marco, I have updated them in the following commit,

https://github.com/PawseySC/pawsey-spack-config/commit/c085b34bbde4ab7b741ca3bdc573fcf561da7c71 

thanks for the reminder

**Comment by marcodelapierre** [comment]
@dipietrantonio we can close this one, isn't it?
