### ISSUE TITLE
Move shpc_registry in system-agnostic location

### ISSUE THREAD

**Issue by marcodelapierre** [PawseySC/pawsey-spack-config#149]
Hi @dipietrantonio ,
it should be possible to move `systems/setonix/shpc_registry` back onto the root dir of this repository, i.e. the same as the `repo` directory. In fact, container module recipes should be system-agnostic.
However, the installation script machinery might need some according update, to use the new location (I suspect it will be in the script to setup shpc).

**Comment by dipietrantonio** [comment]
Hi Marco, the reason it is there is I thought that each system may have a different list of containers to be installed. Now that I think about it, containers to be installed on a given system are listed in the `settings.sh` file anyway. So should we have only a single shpc_registry?

**Comment by marcodelapierre** [comment]
exactly, the container list is in a separate location, these are just pawsey-provided recipes for container modules (if any)

**Comment by dipietrantonio** [comment]
Fixed by https://github.com/PawseySC/pawsey-spack-config/pull/154
