### ISSUE TITLE
Spack version update

### ISSUE THREAD

**Issue by marcodelapierre** [PawseySC/pawsey-spack-config#166]
Hi @dipietrantonio, I would recommend updating Spack from `0.19.0` to `0.19.2` for the upcoming stack rebuild on Setonix.
Being a bugfix release, it should not change much the configuration, but on the other hand we will get all of the bug fixes.

**Comment by dipietrantonio** [comment]
Hi @marcodelapierre, thanks for the suggestion. Given the amount of work still to be done and the short timeline, we will stick to 0.19.0 to avoid having to deal with unexpected behaviours and look to move to spack 20 as soon as the July/August deployment is done.
