### ISSUE TITLE
Install openblas outside the environments

### ISSUE THREAD

**Issue by dipietrantonio** [PawseySC/pawsey-spack-config#175]
For some reason, openblas won't compile on the first try. As a temporary solution, we should compile it outside the environments, maybe within a "for loop" that is kept going until done.

**Comment by marcodelapierre** [comment]
does it need a `spack install -j 1` ?

**Comment by dipietrantonio** [comment]
That is what I first thought, however the errors do not point in that direction, and are quite hard to understand. We did several attempts at building in parallel with a varying number of cores and most of the time work, sometimes it doesn't. In any case the solution proposed in https://github.com/PawseySC/pawsey-spack-config/pull/170/commits/0730cccf207ea5a4373d60e9342e98d51fbef4c2 addresses the issue.
