### ISSUE TITLE
Swapping between stacks with `pawseyenv` might be more complicated than initially thought.

### ISSUE THREAD

**Issue by dipietrantonio** [PawseySC/pawsey-spack-config#179]
From my first experiments, swapping the module version does not remove the previous stack. This has something to do with the Cray environment variables. Need to figure out a way to implement swapping in a clean way.

**Comment by marcodelapierre** [comment]
> Note how we have to unload gcc manually after the PrgEnv-gnu. 

That's funny - have you got a sense of the reason?

Apart from that, the shell algorithm you show makes sense, and gives sensible outputs, I would go ahead and document it.

**Comment by dipietrantonio** [comment]
Hi @marcodelapierre thanks for the comment. I actually double checked, and unloading the `PrgEnv-gnu` is not necessary.

The minimal sequence is

```
cdipietrantonio@joey-01:~> module unload gcc/12.2.0 
cdipietrantonio@joey-01:~> module swap pawseyenv/2023.07 pawseyenv/2022.11 

The following have been reloaded with a version change:
  1) pawseyenv/2023.07 => pawseyenv/2022.11

cdipietrantonio@joey-01:~> module load gcc/12.2.0
```

Also the order of `PrgGnu` and `gcc` unloads does not matter as long as we DO NOT try to swap among PrgEnvs during this sequence. Once this sequence is complete, we can swap among PrgEnvs. Thanks for pushing me investigating further.
