### ISSUE TITLE
Custom LLVM recipe causes issues when installing Julia

### ISSUE THREAD

**Issue by dipietrantonio** [PawseySC/pawsey-spack-config#201]
I tried to install Julia on Joey, but this is what I have got:

```
cdipietrantonio@joey-01:~> module load spack/0.19.0 
Note: when this module is unloaded, the shell environment will NOT revert to its original state, and retain some Spack settings. If you need the original shell environment, start a new shell session instead.
cdipietrantonio@joey-01:~> spack install julia
==> Error: Couldn't find patch for package setonix_repo.llvm with sha256: 88ae104b28c6c1a445a2625f2fd34246ea0da6d7298feaac0e9495b5b0e9c909
```
Doing the following (i.e. removing our custom recipe), fixes the issue.
```
spack@joey-01:/software/setonix/2023.07/spack/var/spack/repos/pawsey/packages> mv llvm/ llvm-tmp
```

Probably because of some outdated file in our copy. Given that our recipe only adds newer versions, we should try to remove it now. This should not cause any issue, given that we use `--no-checksum` during our installation process.

**Comment by marcodelapierre** [comment]
were the patch files from the original recipe dir present in the Pawsey recipe dir, too? - this might be causing the issue

**Comment by dipietrantonio** [comment]
That is the issue I believe, but I do not want to start messing around, mixing patches and recipes of different versions. If we can avoid using our own LLVM (and we should be able to) recipe then that is great.

**Comment by marcodelapierre** [comment]
makes sense!
