### ISSUE TITLE
Please bump nextflow version

### ISSUE THREAD

**Issue by marcodelapierre** [PawseySC/pawsey-spack-config#216]
Hi @dipietrantonio , can you please quickly verify that the upcoming Spack deployment allows to install `nextflow@23.04.3` and to run `nextflow info` ?

If so, let's update the version in the environment. This version contains a significant feature addition of mine, i.e. the support for Spack as the software provider.

https://github.com/PawseySC/pawsey-spack-config/blob/8ba218a382d07d88036f32ed95d3ff47341f3308/systems/setonix/environments/utils/spack.yaml#L11

**Comment by dipietrantonio** [comment]
@ddeeptimahanti @pelahi is there any Reframe check we can use to test the new version of NextFlow? Ideally I would install the new version and remove the old one if it works.

**Comment by marcodelapierre** [comment]
if there is no such test, running `nextflow info` and parsing the output could be a simple and representative one. E.g. if the Java dependency is conflicting, this will not work.

**Comment by ddeeptimahanti** [comment]
Sorry @marcodelapierre for the delay.  We have a basic test in nextflow just to ensure it works.

**Comment by marcodelapierre** [comment]
Perfect, thanks @ddeeptimahanti 

Can you also take care of : 

> can you please quickly verify that the upcoming Spack deployment allows to install `nextflow@23.04.3` ?

**Comment by ddeeptimahanti** [comment]
working on it now @marcodelapierre - testing in my account first and running the reframe test

**Comment by ddeeptimahanti** [comment]
https://github.com/PawseySC/pawsey-spack-config/pull/221
