### ISSUE TITLE
Hyperbeam does not install the `mwa_full_embedded_element_pattern.h5`

### ISSUE THREAD

**Issue by dipietrantonio** [PawseySC/pawsey-spack-config#282]
The file should be installed with hyperbeam and then the module should export the variable `MWA_BEAM_FILE` pointing to the full path of the file.

**Comment by d3v-null** [comment]
There is no official MWA beam files that suits all applications. different groups use different beam files with varying resolution as a tradeoff between performance and accuracy.

**Comment by dipietrantonio** [comment]
@d3v-null that is great idea. We should talk about it more in our meeting.

**Comment by dipietrantonio** [comment]
This has been implemented.
